### ISSUE TITLE
Scrapy project + Firestore Images

### ISSUE THREAD

**Issue by nilan01** [TheATeam-566/Hermit#29]
- [ ] Create a Scrapy based project to grab The Cheesecake Factories menu.
- [ ] Furthermore, we need to grab all the images of the food items and store them somewhere in Firestore as to utilize our DB and not theirs.

This project can occur whenever, though most likely it'll be the last thing we do for Release 1.0.

**Comment by chrispinkney** [comment]
Closing as this is no longer necessary.
