### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by chrispinkney** [TheATeam-566/Hermit#65]
We need a login page to log into the app. This will likely be one of the most challenging aspects of the project. Additionally, a lot of other components are going to rely on some of this functionality (header for name, image, address, etc), so I think this should come sooner rather than later.

1. We're going to (_for starters_) use `PassportJS` and `Google OAuth2.0` for user authentication.
2. With the user info now returned we're going to need to persist this information to the DB (i.e. _create user_)
3. We also need a sign in button that navigates to the correct route.

- [x] login page
  - [x] Hermit logo
  - [x] Google Login button
- [x] Passport integration & passport strategy
  - [x] Google Oauth2.0 integration
  - [x] Persist user account w/ authentication from oauth2.0
  - [x] Firestore user schema

**Comment by chrispinkney** [comment]
sdfsadfasdga

**Comment by nilan01** [comment]
Chris and I are now able to access Google sign in via backend `localhost:8000/auth/google`.

The challenge we are having now, is that after signing via Google sign in, we need to provide a User object to the callback. We currently do not have a User object defined in the Firestore database, therefore we can not provide the callback with a User object.

This brings up a few major challenges for us to solve in the immediate future. We should focus on designing our NoSQL database to handle (Users, UserOrderHistory, etc.).

**Roadblock** for this particular issue? Retrieving User data from our Firestore Database to be provided to the Google sign-in callback.
