### ISSUE TITLE
Add stripe integration

### ISSUE THREAD

**Issue by chrispinkney** [TheATeam-566/Hermit#92]
We're making good progress with the cart (and modal) flow, items are being added to the cart, the last step we need to do is increase and decrease the quantity.

With this issue coming to a close we should now focus our attention on implementing stripe so a user can put an order through.

**Comment by nilan01** [comment]
We've completed implementing the cart. Items are being added to the cart, and a modal opens whenever the cart is clicked which will display all added items as well as their associated quantities. 

Quantities can be increased or decrease onClick().

**Comment by nilan01** [comment]
We are now ready to work with the [Stripe API.](https://stripe.com/docs/api)

This includes:

- [ ] creating a service account with Stripe API
- [ ] reading documentation
- [ ] learning how to send payment requests to the client (frontend)
- [ ] entering payment information to Stripe
- [ ] receiving payment confirmation from Stripe

**Comment by chrispinkney** [comment]
Closed by #112
